name: vokabeltrainer_app
description: Ein einfacher Vokabeltrainer
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # CSV-Parsing
  csv: ^5.1.1
  # OpenStreetMap-Karte + Marker/Polyline
  flutter_map: ^6.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/                       # Level-Bilder
    - assets/Vokabeln alle.csv    # â† Hier wird Deine CSV eingebunden
    - assets/Stationenbeschreibung-englisch.csv
